import Head from "next/head";
import conectarDB from "../lib/dbConnect";
import Movie from "@/models/Movie";
import Link from "next/link";

export default function Home({ movies }) {
  //console.log(movies);
  return (
    <div>
      <Head>
        <title>Short notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/noba.ico" />
      </Head>
      <main className="container">
        <h1 className="text-light">Notes</h1>
        <Link legacyBehavior href="/new">
          <a className="btn btn-primary w80 mb-2">Add note</a>
        </Link>
        {movies.map(({ _id, cuenta, concepto, valor }) => (
          <div className="card mb-2 bg-dark text-light" key={_id}>
            <div className="car-body ">
              <div className="h5 text-uppercase">{cuenta}</div>
              <p className="fw-light">{concepto}</p>
              <p className="fw-light">{valor}</p>

              <Link legacyBehavior href={`/${_id}`}>
                <a className="btn btn-success btn-sm">Detail...</a>
              </Link>
            </div>
          </div>
        ))}
      </main>
    </div>
  );
}
//utilizamos SSR renderizamos en el servidor
//el servidor trae los datos y lo pintamos en el servidor
export async function getServerSideProps() {
  try {
    await conectarDB();
    const res = await Movie.find({});
    const movies = res.map((doc) => {
      const movie = doc.toObject();
      movie._id = `${movie._id}`;
      return movie;
    });
    return { props: { movies } };
  } catch (error) {
    console.log(error);
  }
}
